### ISSUE TITLE
[HTML]Create the main page

### ISSUE THREAD

**Issue by jgkang9402** [Jayone12/pig-game#14]
##Tasks

Create the main page

- [x] Create the main page layout

- [x] Player1, Player2 screen composition on the screen

- [x] Create a cumulative score and total score display area for each player

- [x] Create dice role button, hold button

- [x] Create style sheet
