### ISSUE TITLE
[JavaSript] Create a dice roll function

### ISSUE THREAD

**Issue by talentforest** [Jayone12/pig-game#7]
##Tasks

Create pig-dice-game
- [x] Generate random numbers from 1 to 6
- [x] Return the dice result value
- [x]  A value of 1 returns 0 score
