### ISSUE TITLE
[JavaScript] Returns the result as an accumulated value

### ISSUE THREAD

**Issue by JJKEB** [Jayone12/pig-game#8]
##Tasks

### Returns the result as an accumulated value

- [x] Get player's accumulated value
- [x] If the accumulated value exceeds 100 when you press the hold button, you win, otherwise it is the next turn.
- [x] Next turn when the hold button is clicked
