### ISSUE TITLE
[HTML] Create the main page

### ISSUE THREAD

**Issue by JJKEB** [Jayone12/pig-game#9]
##Tasks

### Create the main page

 - [ ] Create the main page layout
 - [ ] Player1, Player2 screen composition on the screen
 - [ ] Create a cumulative score and total score display area for each player
 - [ ] Create dice role button, hold button
 - [ ] Create style sheet
